# Generated by Django 4.2.2 on 2023-06-14 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_tags_tags_articletags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletags',
            options={'verbose_name': 'Тег статьи', 'verbose_name_plural': 'Теги статьи'},
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='tags',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='articletags',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arc', to='articles.tags', verbose_name='Тег'),
        ),
    ]
