# Generated by Django 4.2.2 on 2023-06-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_tag_alter_articletags_options_articletags_is_main_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletags',
            options={'ordering': ['is_main'], 'verbose_name': 'тег статьи', 'verbose_name_plural': 'теги статьи'},
        ),
        migrations.AlterField(
            model_name='articletags',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='основной'),
        ),
    ]
