# Generated by Django 4.2.2 on 2023-06-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_articletags_options_alter_articletags_is_main'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleTags',
            new_name='Scopes',
        ),
    ]
