# Generated by Django 4.2.2 on 2023-06-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_articletags_scopes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='scopes',
            old_name='tags',
            new_name='tag',
        ),
    ]
